### ISSUE TITLE
jeremeamia/superclosure abandoned

### ISSUE THREAD

**Issue by cyrnetix** [WyriHaximus/reactphp-child-process-closure#20]
I just got the message in composer that the vendor jeremeamia/superclosure is abandoned. Can this be changed to opis/closure?

**Comment by WyriHaximus** [comment]
It should be fairly simple to do that, would you mind creating a PR for that?

**Comment by cyrnetix** [comment]
I replace the vendor and tested it with my own projects, didn't find any issues.

**Comment by WyriHaximus** [comment]
Great! Just release [`1.1.0`](https://github.com/WyriHaximus/reactphp-child-process-closure/releases/tag/1.1.0) with your fix in it. Thanks :+1: !
