### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by yousafsyed** [WyriHaximus/reactphp-child-process-closure#30]
Hello, are you planning to upgrade this package to provide support for PHP8? what is missing this package to run this with PHP8, I am working on a small expressive HTTP framework that is built on top of reactPHP and swoolePHP.

My package requires to run closures in child-processes. [crowPHP](https://github.com/crowphp/crow) on GitHub, its will in a very early development phase, I am coming from nodejs background and found reactPHP really fascinating

**Comment by WyriHaximus** [comment]
Ultimately I want to provide PHP 8 support for all my packages. But currently, I'm updating on a per requested or personal need basis.

In short, a few things need to be done to get PHP 8 support in:
* Include 8 in the `php` version range in `composer.json`
* All dependencies must also support PHP 8
* Code must work on PHP 8

**Comment by yousafsyed** [comment]
Thanks
